worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
	
    upstream rtc_service {
        server rtc1:8086;  # Backend server 1
        server rtc2:8087;  # Backend server 2
        # Bạn có thể thêm nhiều server khác nếu cần
    }

    map $http_upgrade $connection_upgrade {
	default Upgrade;
	'' close;
    }

    server {
	listen       8080;
        server_name  localhost;
        location /chat {

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' '*' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;

            proxy_pass http://rtc_service;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;

            proxy_connect_timeout 7d;
            proxy_send_timeout 7d;
            proxy_read_timeout 7d;
        }

        location /services/ {

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' '*' always;
            add_header 'Access-Control-Allow-Headers' '*' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;

            # Xử lý các yêu cầu OPTIONS (Preflight)
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://gateway:8081/services/;  # Chuyển tiếp yêu cầu đến server 8081, giữ lại phần sau /services
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }	
}