server:
  port: 8086
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 1 #16384
      linger-ms: 200
      buffer-memory: 33554432
#    consumer:
#      group-id: my-group-id
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
##      enable-auto-commit: true
##      auto-commit-interval: 1000
#      auto-offset-reset: earliest
#      bootstrap-servers: localhost:9092

#    properties:
#      delivery.timeout.ms: 180000
#      request.timeout.ms: 60000
#      enable.idempotence: true
#      max.in.flight.requests.per.connection: 5
    admin:
#      fail-fast: true
      properties:
        bootstrap-servers: localhost:9092
#        retries: 5
#        retry.backoff.ms: 1000
  jpa:
#    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.lob.non_contextual_creation: true
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: 101119
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10