server:
  port: 8088
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # service name to lower-case in url
          predicates:
            - name: Path
              args:
                pattern: "'/services/' + serviceId + '/**'"   ## config pattern accept call api
          filters:
            - name: RewritePath
              args:
                regexp: "'/services/' + serviceId + '/?(?<remaining>.*)'" ## replacement path to routing service
                replacement: "'/${remaining}'"
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
