server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #          routeIdPrefix: "no/"
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'service/' + serviceId + '/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'service/' + serviceId + '/?(?<remaining>.*)'"
                replacement: "'/${remaining}'"
