server:
  port: 8086
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  sleuth:
    sampler:
      probability: 1.0  # Always sample requests for tracing
    zipkin:
      base-url: http://localhost:9411  # Zipkin server URL (update if needed)
      enabled: true
  application:
    name: user-service
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.lob.non_contextual_creation: true
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: 101119
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
