global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "springboot-learning"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "api-service:8086"
        labels:
          application: "learning"
